apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    env:
      - name: CUSTOM_DATA
        valueFrom:
          configMapKeyRef:
            name: nginx-config
            key: custom_data
  restartPolicy: Always
